### ISSUE TITLE
The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found.

### ISSUE THREAD

**Issue by Rathish100** [Mina-Mikhail/Kotlin-Base-MVVM#5] opened 2021-10-20 13:02 UTC
When I checkout and while syncing I'm getting error

"The Hilt Android Gradle plugin is applied but no com.google.dagger:hilt-android dependency was found."

**Comment by Mina-Mikhail** [comment] 2021-10-23 22:43
Duplicate of #4

**Closed as completed by Mina-Mikhail** 2021-10-23 22:43 UTC
